name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:

      test_db:
        image: postgres:12
        env:
          POSTGRES_DB: test_db
          POSTGRES_HOST: localhost
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test123

        ports:
        - 5680:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup cache
      uses: actions/cache@v1
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Tests
      run: |
        MYPYPATH=. pytest --mypy --black --isort  --cov=nimbus --cov-report=xml --cov-report=term
